# Generated by Django 5.1.5 on 2025-02-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wokesdlPages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='accessCode',
            field=models.CharField(default='mob', max_length=500),
            preserve_default=False,
        ),
    ]
