# Generated by Django 5.1.5 on 2025-02-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wokesdlPages', '0002_imageset_accesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='count_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
