# Generated by Django 5.1.5 on 2025-04-12 22:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wokesdlPages', '0004_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('order_notes', models.TextField(blank=True)),
                ('street_address_1', models.CharField(max_length=255, null=True, verbose_name='Street Address Line 1')),
                ('street_address_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address Line 2 (optional)')),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=20, null=True)),
                ('destination_country', models.CharField(max_length=100, null=True)),
                ('additional_info', models.TextField(blank=True)),
                ('amount', models.PositiveIntegerField(blank=True)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('delivery_price', models.IntegerField(default=0)),
                ('delivered', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
