# Generated by Django 5.1.5 on 2025-05-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wokesdlPages', '0007_contact_sizeset_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactRequest',
        ),
    ]
