# Generated by Django 5.1.5 on 2025-05-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wokesdlPages', '0008_rename_contact_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
